services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_docker_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://symfony:secret@mysql:3306/app?serverVersion=8.0"
    depends_on:
      - mysql
  #      - redis

  web:
    image: nginx:alpine
    container_name: symfony_docker_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: symfony_docker_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: symfony_docker_mailhog
    ports:
      - "8025:8025" # Web interface MailHog
      - "1025:1025" # SMTP-сервер

#  redis:
#    image: redis:alpine
#    container_name: symfony_docker_redis
#    restart: unless-stopped

#  node:
#    image: node:20-alpine
#    container_name: symfony_docker_node
#    working_dir: /var/www
#    volumes:
#      - .:/var/www
#    entrypoint: ["tail", "-f", "/dev/null"]